update: 更新文件 HPKBUILD
Signed-off-by: xiao-yanghang <yhxiaom@isoftstone.com>

diff --git a/thirdparty/libbacktrace/pr/HPKBUILD b/thirdparty/libbacktrace/pr/HPKBUILD
--- a/thirdparty/libbacktrace/pr/HPKBUILD
+++ b/thirdparty/libbacktrace/pr/HPKBUILD
@@ -22,10 +22,10 @@ archs=("armeabi-v7a" "arm64-v8a" "x86_64")
 license=()
 depends=()
 makedepends=()
-source="https://github.com/ianlancetaylor/$pkgname/archive/refs/heads/master.tar.gz"
+source="https://github.com/ianlancetaylor/libbacktrace.git"
 
-autounpack=true
-downloadpackage=true
+autounpack=false
+downloadpackage=false
 builddir=$pkgname-master
 packagename=$builddir.tar.gz
 buildtools="configure"
@@ -33,7 +33,29 @@ buildtools="configure"
 source envset.sh
 host=
 
+cloneflag=true
 prepare() {
+    if $cloneflag
+    then
+        git clone $source $builddir
+        ret=$?
+        if [ $ret -ne 0 ]; then
+            echo "fail: git clone $source $builddir $ret"
+            return $ret
+        fi
+
+        cd  $builddir
+        git checkout -b b9e40069c0b47a722286b94eb5231f7f05c08713 b9e40069c0b47a722286b94eb5231f7f05c08713
+        ret=$?
+        if [ $ret -ne 0 ]; then
+            echo "fail: git checkout $pkgver $ret"
+            return $ret
+        fi
+
+        cd $OLDPWD
+        cloneflag=false 
+    fi
+    
     mkdir -p $builddir/$ARCH-build
     if [ $ARCH == "armeabi-v7a" ]
     then
