update: 更新文件 HPKBUILD
Signed-off-by: xiao-yanghang <yhxiaom@isoftstone.com>

diff --git a/thirdparty/libbacktrace/pr/HPKBUILD b/thirdparty/libbacktrace/pr/HPKBUILD
--- a/thirdparty/libbacktrace/pr/HPKBUILD
+++ b/thirdparty/libbacktrace/pr/HPKBUILD
@@ -52,6 +52,13 @@ prepare() {
             return $ret
         fi
 
+        git submodule update --init --recursive
+        ret=$?
+        if [ $ret -ne 0 ]; then
+            echo "fail: git submodule update --init $ret"
+            return $ret
+        fi
+
         cd $OLDPWD
         cloneflag=false 
     fi
