NFD的测试脚本添加前置条件
Signed-off-by: handong <18335786818@163.com>

diff --git a/thirdparty/NFD/HPKCHECK b/thirdparty/NFD/HPKCHECK
--- a/thirdparty/NFD/HPKCHECK
+++ b/thirdparty/NFD/HPKCHECK
@@ -17,55 +17,75 @@
 source HPKBUILD > /dev/null 2>&1
 logfile=${LYCIUM_THIRDPARTY_ROOT}/${pkgname}/${pkgname}_${ARCH}_${OHOS_SDK_VER}_test.log
 
+prepare_test_env() {
+    [ "$EUID" -ne 0 ] && { echo "Root required"; exit 1; }
+    SRC="${TPC_SRC:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)}"
+    [ ! -d "$SRC/thirdparty" ] && { echo "Invalid source"; exit 1; }
+
+    DEST="/data/tpc_c_cplusplus"
+    rm -rf "$DEST"
+    cp -r "$SRC" "$DEST" || exit 1
+
+    getent group daemon >/dev/null || echo "daemon:x:1:" >> /etc/group
+    getent passwd daemon >/dev/null || echo "daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin" >> /etc/passwd
+
+    NFD_SRC=$(find "$DEST/thirdparty/NFD" -maxdepth 1 -type d -name "NFD-*" | head -1)
+    BUILD_DIR="$NFD_SRC/${ARCH}-build"
+    [ -d "$BUILD_DIR" ] && chown -R daemon:daemon "$BUILD_DIR"
+
+    cd "$DEST/thirdparty/NFD" || exit 1
+}
+
 openharmonycheck() {
-   cd $builddir/$ARCH-build
+    prepare_test_env
+    cd $builddir/$ARCH-build
 
-   echo "\n unit-tests-core test begin" > ${logfile} 2>&1
-   ./unit-tests-core >> $logfile 2>&1
-   res=$?
-   if [ $res -ne 0 ]; then
-       cd $OLDPWD
-       return $res
-   fi
+    echo "\n unit-tests-core test begin" > ${logfile} 2>&1
+    ./unit-tests-core >> $logfile 2>&1
+    res=$?
+    if [ $res -ne 0 ]; then
+        cd $OLDPWD
+        return $res
+    fi
 
-   echo "\n unit-tests-tools test begin" >> ${logfile} 2>&1
-   ./unit-tests-tools >> $logfile 2>&1
-   res=$?
-   if [ $res -ne 0 ]; then
-       cd $OLDPWD
-       return $res
-   fi
+    echo "\n unit-tests-tools test begin" >> ${logfile} 2>&1
+    ./unit-tests-tools >> $logfile 2>&1
+    res=$?
+    if [ $res -ne 0 ]; then
+        cd $OLDPWD
+        return $res
+    fi
 
-   echo "\n cs-benchmark test begin" >> ${logfile} 2>&1
-   ./cs-benchmark >> $logfile 2>&1
-   res=$?
-   if [ $res -ne 0 ]; then
-       cd $OLDPWD
-       return $res
-   fi
+    echo "\n cs-benchmark test begin" >> ${logfile} 2>&1
+    ./cs-benchmark >> $logfile 2>&1
+    res=$?
+    if [ $res -ne 0 ]; then
+        cd $OLDPWD
+        return $res
+    fi
 
-   echo "\n pit-fib-benchmark test begin" >> ${logfile} 2>&1
-   ./pit-fib-benchmark >> $logfile 2>&1
-   res=$?
-   if [ $res -ne 0 ]; then
-       cd $OLDPWD
-       return $res
-   fi
+    echo "\n pit-fib-benchmark test begin" >> ${logfile} 2>&1
+    ./pit-fib-benchmark >> $logfile 2>&1
+    res=$?
+    if [ $res -ne 0 ]; then
+        cd $OLDPWD
+        return $res
+    fi
 
-   echo "\n unit-tests-daemon test begin" >> ${logfile} 2>&1
-   ./unit-tests-daemon -t !Face/TestUnixStreamChannel -t !Mgmt/TestGeneralConfigSection >> $logfile 2>&1
-   res=$?
-   if [ $res -ne 0 ]; then
-       cd $OLDPWD
-       return $res
-   fi
+    echo "\n unit-tests-daemon test begin" >> ${logfile} 2>&1
+    ./unit-tests-daemon -t !Face/TestUnixStreamChannel -t !Mgmt/TestGeneralConfigSection >> $logfile 2>&1
+    res=$?
+    if [ $res -ne 0 ]; then
+        cd $OLDPWD
+        return $res
+    fi
 
-   ./unit-tests-daemon -t Mgmt/TestGeneralConfigSection >> $logfile 2>&1
-   res=$?
-   if [ $res -ne 0 ]; then
-       cd $OLDPWD
-       return $res
-   fi
-   cd $OLDPWD
-   return $res
+    ./unit-tests-daemon -t Mgmt/TestGeneralConfigSection >> $logfile 2>&1
+    res=$?
+    if [ $res -ne 0 ]; then
+        cd $OLDPWD
+        return $res
+    fi
+    cd $OLDPWD
+    return $res
 }
