修改以下review问题： 1、patch文件名修改 2、BUILD中patch flag放到前面 3、构建测试用例放到check函数
Signed-off-by: kami_coder <1009097140@qq.com>

diff --git a/thirdparty/libice/HPKBUILD b/thirdparty/libice/HPKBUILD
--- a/thirdparty/libice/HPKBUILD
+++ b/thirdparty/libice/HPKBUILD
@@ -41,6 +41,23 @@ patchflag=true
 host=
 
 prepare() {
+    if $patchflag
+    then
+        patch -p1 < `pwd`/libice_ohos_pkg.patch > $publicbuildlog 2>&1
+        if [ $? -ne 0 ]
+        then
+            echo "patch failed"
+            return -1
+        fi
+        
+        cd $builddir
+        patch -p1 < `pwd`/../libice_ohos_test.patch >> $publicbuildlog 2>&1
+        cd $OLDPWD
+        
+        # patch只需要打一次,关闭打patch
+        patchflag=false
+    fi
+    
     cp -rf $builddir $builddir-$ARCH-build
     if [ $ARCH == "armeabi-v7a" ]
     then
@@ -55,19 +72,8 @@ prepare() {
         return -1
     fi
     export CFLAGS="-I$PKGBUILD_ROOT $CFLAGS"
-
-    if $patchflag
-    then
-        rm -rf `pwd`/X11
-        patch -p1 < `pwd`/libice_head.patch > $buildlog 2>&1
-        # X11 patch只需要打一次,关闭打patch
-        patchflag=false
-    fi
-    
-    cd $builddir-$ARCH-build
-    patch -p1 < `pwd`/../libice_pkg.patch
-    cd $OLDPWD
 }
+
 # "error: must install xorg-macros": sudo apt-get install xutils-dev
 build() {
     cd $builddir-$ARCH-build
@@ -75,19 +81,7 @@ build() {
     $MAKE >> $buildlog 2>&1
     ret=$?
     cd $OLDPWD
-    if [ $ret -ne 0 ]; then
-        return $ret
-    fi
 
-    cd $builddir-$ARCH-build/example
-    if [ "$ARCH" = "armeabi-v7a" ]
-    then
-        ${OHOS_SDK}/native/llvm/bin/clang --target=arm-linux-ohos --sysroot=${OHOS_SDK}/native/sysroot -march=armv7a main_test.c -I../include/X11/ICE/ -I../.. -I../src -I../include -L../src/.libs -lICE -o icetest
-    else
-        ${OHOS_SDK}/native/llvm/bin/clang --target=aarch64-linux-ohos --sysroot=${OHOS_SDK}/native/sysroot main_test.c -I../include/X11/ICE -I../.. -I../src -I../include -L../src/.libs -lICE -o icetest
-    fi
-    
-    cd $OLDPWD
     return $ret
 }
 
@@ -95,12 +89,31 @@ package() {
     cd $builddir-$ARCH-build
     $MAKE install >> $buildlog 2>&1
     ret=$?
-    cp -rf ../X11/* ../../../lycium/usr/libice/$ARCH/include/X11/
+    cp -rf ../X11/* ${LYCIUM_ROOT}/usr/libice/$ARCH/include/X11/
     cd $OLDPWD
     return $ret
 }
 
 check() {
+    cd $builddir-$ARCH-build/example
+    if [ "$ARCH" = "armeabi-v7a" ]
+    then
+        ${OHOS_SDK}/native/llvm/bin/clang main_test.c \
+            --target=arm-linux-ohos --sysroot=${OHOS_SDK}/native/sysroot -march=armv7a \
+            -I../include/X11/ICE/ -I../.. -I../src -I../include \
+            -L../src/.libs -lICE -o icetest
+    elif [ "$ARCH" = "arm64-v8a" ]
+    then
+        ${OHOS_SDK}/native/llvm/bin/clang main_test.c \
+            --target=aarch64-linux-ohos --sysroot=${OHOS_SDK}/native/sysroot \
+            -I../include/X11/ICE -I../.. -I../src -I../include \
+            -L../src/.libs -lICE -o icetest
+    else
+        echo "Not support ${ARCH}"
+        return -1
+    fi
+    
+    cd $OLDPWD
     echo "The test must be on an OpenHarmony device!"
 }
 
@@ -120,5 +133,5 @@ recoverpkgbuildenv() {
 
 # 清理环境
 cleanbuild() {
-    rm -rf ${PWD}/$builddir $builddir-armeabi-v7a-build $builddir-arm64-v8a-build #${PWD}/$packagename  
+    rm -rf ${PWD}/$builddir ${PWD}/$builddir-armeabi-v7a-build ${PWD}/$builddir-arm64-v8a-build ${PWD}/X11
 }
